name: Test All

on:
  workflow_call:

jobs:
  # test-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build and test backend
  #       run: |
  #         cd infra
  #         docker compose -f compose.ci.yml build test-backend
  #         docker compose -f compose.ci.yml run --rm test-backend

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test frontend
        run: |
          cd infra
          docker compose -f compose.ci.yml build test-frontend
          docker compose -f compose.ci.yml run --rm test-frontend
